---
title: "Association between ABO-related SVs and microbiome composition"
author: "Daoming Wang"
date: "2021/03/27"
output:
  html_document: 
    theme: flatly
    highlight: espresso
    toc: true
    toc_depth: 4
    toc_float: true
  word_document: default
  pdf_document:
    includes:
      in_header: header.tex
      keep_tex: yes
      latex_engine: xelatex
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 Preparation
### 1.1 Import

```{r 1.1, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
suppressMessages(source("functions.R"))
```

### 1.2 Inputs

```{r 1.2, echo=TRUE}
mbio_dag3_allTax<-read.csv("../../Dataset/rawdata/DAG3_microbiome/DAG3_metaphlan_bacteria_archaea_filtered_v2.txt",sep = "\t",row.names = "ID", check.names = F)
path_dag3<-read.csv("../../Dataset/rawdata/DAG3_microbiome/DAG3_humann_Metacyc_filtered_v2.txt",sep = "\t",row.names = "ID", check.names = F)
load("01.cleanData/assoc_SV/dsgv_dag3_abo.RData")
load("01.cleanData/assoc_SV/vsgv_dag3_abo.RData")
load("01.cleanData/blood_type/bt_dag3.RData")

load("../../202201_DAG3_SV/DAG3_SV/01.cleanData/phen/dag3_covar.RData")
```


## 2 Association between ABO-related SVs and microbiome overall composition

### 2.1 Extract species 

```{r 2.1}
mbio_dag3<-prepData(mbio_dag3_allTax, getLevel="S",isHMP2=T) 
mbio_dag3<-shortenNames(mbio_dag3, sep = "\\.",direction = 1)
bt_dag3 <- na.omit(bt_dag3)
if(!dir.exists("04.SV_abun/")){dir.create("04.SV_abun/")}
sv_dag3_abo<-cbind(dsgv_dag3_abo, vsgv_dag3_abo) %>% na.omit

bt_sv_dag3_abo.inter<-intersect(rownames(bt_dag3), rownames(sv_dag3_abo))
mbio_bt_sv_dag3_abo.inter<-intersect(bt_sv_dag3_abo.inter, rownames(mbio_dag3))

sv_dag3_abo.rmna<- sv_dag3_abo %>% .[match(mbio_bt_sv_dag3_abo.inter, rownames(.)),]
bt_dag3.rmna<- bt_dag3 %>% .[match(mbio_bt_sv_dag3_abo.inter, rownames(.)),]
mbio_dag3.rmna<- mbio_dag3 %>% .[match(mbio_bt_sv_dag3_abo.inter, rownames(.)),]
path_dag3.rmna<- path_dag3 %>% .[match(mbio_bt_sv_dag3_abo.inter, rownames(.)),]
bt_sv_dag3_abo.rmna<-cbind(bt_dag3.rmna, sv_dag3_abo.rmna)
```

### 2.2 Association
```{r 2.2}

#sgv_dag3_abo.inter<-sgv_dag3_abo[match(rownames(mbio_dag3), rownames(sgv_dag3_abo)),]
#rownames(sgv_dag3_abo.inter)<-rownames(mbio_dag3)

#bt_dag3.inter<-bt_dag3[match(rownames(mbio_dag3), rownames(bt_dag3)),]
#rownames(bt_dag3.inter)<-rownames(mbio_dag3)
#bt_dag3.inter$sample<-rownames(mbio_dag3)

# species abundance
mbio_dag3_dist<-vegdist(mbio_dag3.rmna, method = "bray")
#mbio_dag3_pcoa_res<-pcoa(mbio_dag3_dist, correction="cailliez")
#save(mbio_dag3_pcoa_res, file = "04.SV_abun/mbio_dag3_pcoa_res.RData")
load("04.SV_abun/mbio_dag3_pcoa_res.RData")
mbio_dag3_pcoa <- data.frame(mbio_dag3_pcoa_res$vectors.cor[,c(1:5)])

#sgv_dag3_abo.rmna<-na.omit(sgv_dag3_abo.inter)
#sgv_dag3_abo.rmna.interSample<-intersect(rownames(sgv_dag3_abo.rmna), rownames(mbio_dag3_pcoa))
#mbio_dag3_dist.rmna<-mbio_dag3_dist %>% as.matrix %>% .[rownames(sgv_dag3_abo.rmna),rownames(sgv_dag3_abo.rmna)]
mbio_dag3_dist.mat<-mbio_dag3_dist %>% as.matrix 
mbio_sgv_abo_dag3.adonis <- adonis2(mbio_dag3_dist ~ A_antigen + B_antigen + FUT2_secretor_status + A_antigen * FUT2_secretor_status + B_antigen * FUT2_secretor_status + `Faecalibacterium cf. prausnitzii KLE1255:577_579` + `Faecalibacterium cf. prausnitzii KLE1255:1154_1155` + `Faecalibacterium cf. prausnitzii KLE1255:575_577` + `Faecalibacterium cf. prausnitzii KLE1255:2910_2911` + `Faecalibacterium cf. prausnitzii KLE1255:885_887`,data = bt_sv_dag3_abo.rmna)
save(mbio_sgv_abo_dag3.adonis, file = "04.SV_abun/mbio_sgv_abo_dag3.adonis.RData")

mbio_sgv_abo_dag3.adonis.r2<-mbio_sgv_abo_dag3.adonis[c(1,2,3,9,10,4:8),c(3,5)]
rownames(mbio_sgv_abo_dag3.adonis.r2)<-c("A-antigen", "B-antigen", "FUT2 secretor", "A-antigen × FUT2 secretor","B-antigen × FUT2 secretor",
                                         "577_579", "1154_1155", "575_577", "2910_2911", "885_887")
mbio_sgv_abo_dag3.adonis.r2$Significant<-"No"
mbio_sgv_abo_dag3.adonis.r2$Significant[mbio_sgv_abo_dag3.adonis.r2$`Pr(>F)`<0.05]<-"Yes"
mbio_sgv_abo_dag3.adonis.r2$Significant<-factor(mbio_sgv_abo_dag3.adonis.r2$Significant, levels = c("Yes", "No"))
mbio_sgv_abo_dag3.adonis.r2$Variable<-factor(rownames(mbio_sgv_abo_dag3.adonis.r2), levels = rownames(mbio_sgv_abo_dag3.adonis.r2))

write.table(mbio_sgv_abo_dag3.adonis.r2,"04.SV_abun/mbio_sgv_abo_dag3.adonis.r2.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

if(!dir.exists("04.SV_abun/")){dir.create("04.SV_abun/")}
pdf("04.SV_abun/mbio_sgv_abo_dag3.adonis.r2.pdf", width = 5, height = 4)
ggplot(mbio_sgv_abo_dag3.adonis.r2, aes(x=rownames(mbio_sgv_abo_dag3.adonis.r2), y=R2))+
  geom_bar(aes(color = Significant, fill = Significant),position = "stack",stat="identity")+
  xlab(NULL)+
  ylab("R-square")+
  scale_x_discrete(limits = rownames(mbio_sgv_abo_dag3.adonis.r2))+
  scale_y_continuous(expand = c(0,0))+
  scale_fill_npg()+
  scale_color_npg()+
  theme(plot.subtitle = element_text(vjust = 1), 
        plot.caption = element_text(vjust = 1), 
        plot.margin=unit(c(1,1,1,1),"cm"),
        axis.line.x =  element_line(),
        axis.line.y = element_line(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        #legend.position="top",
        legend.key = element_rect(fill = NA), 
        legend.text = element_text(size = 10),
        panel.grid.major = element_line(colour = NA,linetype = "dashed",size = 0.25),
        panel.grid.minor = element_line(colour = NA), 
        panel.background = element_rect(fill = NA))
dev.off()


pdf("04.SV_abun/p_sv_mbio_pcoa.pdf",width = 5, height = 5)
for(i in 1:ncol(sv_dag3_abo.rmna)){
#  i<-1
  p_F.prau_pcoa<-ggplot(mbio_dag3_pcoa,aes(Axis.1,Axis.2, color = sv_dag3_abo.rmna[,i]))+
    geom_point(size = 2,alpha = 0.5)+
    xlab(paste("PCo1=",round(100*mbio_dag3_pcoa_res$values$Rel_corr_eig[1],digits = 2),"%",sep = ""))+
    ylab(paste("PCo2=",round(100*mbio_dag3_pcoa_res$values$Rel_corr_eig[2],digits = 2),"%",sep = ""))+
    ggtitle(colnames(sv_dag3_abo.rmna)[i])+
    scale_color_distiller(palette = "Spectral")+
    theme(plot.subtitle = element_text(vjust = 1), 
          plot.caption = element_text(vjust = 1), 
          axis.line.x =  element_line(),
          axis.line.y = element_line(),
          legend.position = 'right',
          legend.title = element_blank(),
          legend.key = element_rect(fill = NA), 
          panel.grid.major = element_line(colour = NA),
          panel.grid.minor = element_line(colour = NA),
          panel.background = element_rect(fill = NA))
  
  print(p_F.prau_pcoa)
  
}
dev.off()

# dbrda
sgv_dag3_abo.rmna.input<-sgv_dag3_abo.rmna
colnames(sgv_dag3_abo.rmna.input)<-colnames(sgv_dag3_abo.rmna.input)%>%str_replace_all(".*\\:", "")
bt_dag3.rmna<-bt_dag3[match(rownames(sgv_dag3_abo.rmna), rownames(bt_dag3)),]

mbio_sgv_abo_dag3.dbrda<-dbrda(as.dist(mbio_dag3_dist.rmna)~.,data = sgv_dag3_abo.rmna.input)
mbio_sgv_abo_dag3.dbrda.anova<-anova(mbio_sgv_abo_dag3.dbrda, by="terms")
save(mbio_sgv_abo_dag3.dbrda, file = "04.SV_abun/mbio_sgv_abo_dag3.dbrda.RData")
save(mbio_sgv_abo_dag3.dbrda.anova, file = "04.SV_abun/mbio_sgv_abo_dag3.dbrda.anova.RData")

p_mbio_sgv_abo_dag3.dbrda<-ggord(mbio_sgv_abo_dag3.dbrda, bt_dag3.rmna$Bloodtype, #vec_lab = new_lab,
      veccol = 'grey50',alpha_el = 0.05,alpha = 0.5,txt = 3,size = 1.5,ext = 1.03,repel = T,labcol = '#e63946',ellipse = FALSE)+
  theme(plot.subtitle = element_text(vjust = 1), 
        plot.caption = element_text(vjust = 1), 
        axis.line.x =  element_line(),
        axis.line.y = element_line(),
        legend.position = 'bottom',
        legend.title = element_blank(),
        legend.key = element_rect(fill = NA), 
        panel.grid.major = element_line(colour = NA),
        panel.grid.minor = element_line(colour = NA),
        panel.background = element_rect(fill = NA))

pdf("04.SV_abun/p_sv_mbio_dbrda.pdf",width = 5, height = 5)
print(p_mbio_sgv_abo_dag3.dbrda)
dev.off()

# pathway abundance
path_dag3_dist<-vegdist(path_dag3.rmna, method = "bray")
#path_dag3_pcoa_res<-pcoa(path_dag3_dist, correction="cailliez")
#save(path_dag3_pcoa_res, file = "04.SV_abun/path_dag3_pcoa_res.RData")
load("04.SV_abun/path_dag3_pcoa_res.RData")
path_dag3_pcoa <- data.frame(path_dag3_pcoa_res$vectors.cor[,c(1:5)])

#sgv_dag3_abo.rmna<-na.omit(sgv_dag3_abo.inter)
#sgv_dag3_abo.rmna.interSample<-intersect(rownames(sgv_dag3_abo.rmna), rownames(path_dag3_pcoa))
path_dag3_dist.rmna<-path_dag3_dist %>% as.matrix # %>% .[rownames(sgv_dag3_abo.rmna),rownames(sgv_dag3_abo.rmna)]
path_sgv_abo_dag3.adonis <- adonis(as.dist(path_dag3_dist.rmna)~A_antigen + B_antigen + FUT2_secretor_status + A_antigen * FUT2_secretor_status + B_antigen * FUT2_secretor_status + `Faecalibacterium cf. prausnitzii KLE1255:577_579` + `Faecalibacterium cf. prausnitzii KLE1255:1154_1155` + `Faecalibacterium cf. prausnitzii KLE1255:575_577` + `Faecalibacterium cf. prausnitzii KLE1255:2910_2911` + `Faecalibacterium cf. prausnitzii KLE1255:885_887`,data = bt_sv_dag3_abo.rmna)
save(path_sgv_abo_dag3.adonis, file = "04.SV_abun/path_sgv_abo_dag3.adonis.RData")

path_sgv_abo_dag3.adonis.r2<-path_sgv_abo_dag3.adonis$aov.tab[c(1,2,3,9,10,4:8),5:6]
write.table(path_sgv_abo_dag3.adonis.r2,"04.SV_abun/path_sgv_abo_dag3.adonis.r2.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

#rownames(path_sgv_abo_dag3.adonis.r2)<-rownames(path_sgv_abo_dag3.adonis.r2)%>%str_replace_all(".*:", "")%>%str_replace_all("`", "")
#sum(path_sgv_abo_dag3.adonis.r2$R2)

#mbio_sgv_abo_dag3.adonis.r2<-mbio_sgv_abo_dag3.adonis[c(1,2,3,9,10,4:8),c(3,5)]
rownames(path_sgv_abo_dag3.adonis.r2)<-c("A-antigen", "B-antigen", "FUT2 secretor", "A-antigen × FUT2 secretor","B-antigen × FUT2 secretor",
                                         "577_579", "1154_1155", "575_577", "2910_2911", "885_887")
path_sgv_abo_dag3.adonis.r2$Significant<-"No"
path_sgv_abo_dag3.adonis.r2$Significant[path_sgv_abo_dag3.adonis.r2$`Pr(>F)`<0.05]<-"Yes"
path_sgv_abo_dag3.adonis.r2$Significant<-factor(path_sgv_abo_dag3.adonis.r2$Significant, levels = c("Yes", "No"))
path_sgv_abo_dag3.adonis.r2$Variable<-factor(rownames(path_sgv_abo_dag3.adonis.r2), levels = rownames(path_sgv_abo_dag3.adonis.r2))

if(!dir.exists("04.SV_abun/")){dir.create("04.SV_abun/")}
pdf("04.SV_abun/path_sgv_abo_dag3.adonis.r2.pdf", width = 4, height = 4,5)

if(!dir.exists("04.SV_abun/")){dir.create("04.SV_abun/")}
pdf("04.SV_abun/path_sgv_abo_dag3.adonis.r2.pdf", width = 5, height = 4)
ggplot(path_sgv_abo_dag3.adonis.r2, aes(x=rownames(path_sgv_abo_dag3.adonis.r2), y=R2))+
  geom_bar(aes(color = Significant, fill = Significant),position = "stack",stat="identity")+
  xlab(NULL)+
  ylab("R-square")+
  scale_x_discrete(limits = rownames(path_sgv_abo_dag3.adonis.r2))+
  scale_y_continuous(expand = c(0,0))+
  scale_fill_npg()+
  scale_color_npg()+
  theme(plot.subtitle = element_text(vjust = 1), 
        plot.caption = element_text(vjust = 1), 
        plot.margin=unit(c(1,1,1,1),"cm"),
        axis.line.x =  element_line(),
        axis.line.y = element_line(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        #legend.position="top",
        legend.key = element_rect(fill = NA), 
        legend.text = element_text(size = 10),
        panel.grid.major = element_line(colour = NA,linetype = "dashed",size = 0.25),
        panel.grid.minor = element_line(colour = NA), 
        panel.background = element_rect(fill = NA))
dev.off()

pdf("04.SV_abun/p_sv_path_pcoa.pdf",width = 5, height = 5)
for(i in 1:ncol(sgv_dag3_abo.inter)){
#  i<-1
  p_F.prau_pcoa<-ggplot(path_dag3_pcoa,aes(Axis.1,Axis.2, color = sgv_dag3_abo.inter[,i]))+
    geom_point(size = 2,alpha = 0.5)+
    xlab(paste("PCo1=",round(100*path_dag3_pcoa_res$values$Rel_corr_eig[1],digits = 2),"%",sep = ""))+
    ylab(paste("PCo2=",round(100*path_dag3_pcoa_res$values$Rel_corr_eig[2],digits = 2),"%",sep = ""))+
    ggtitle(colnames(sgv_dag3_abo.inter)[i])+
    scale_color_distiller(palette = "Spectral")+
    theme(plot.subtitle = element_text(vjust = 1), 
          plot.caption = element_text(vjust = 1), 
          axis.line.x =  element_line(),
          axis.line.y = element_line(),
          legend.position = 'right',
          legend.title = element_blank(),
          legend.key = element_rect(fill = NA), 
          panel.grid.major = element_line(colour = NA),
          panel.grid.minor = element_line(colour = NA),
          panel.background = element_rect(fill = NA))
  
  print(p_F.prau_pcoa)
  
}
dev.off()


# dbrda
path_sgv_abo_dag3.dbrda<-dbrda(as.dist(path_dag3_dist.rmna)~.,data = sgv_dag3_abo.rmna.input)
path_sgv_abo_dag3.dbrda.anova<-anova(path_sgv_abo_dag3.dbrda, by="terms")
save(path_sgv_abo_dag3.dbrda, file = "04.SV_abun/path_sgv_abo_dag3.dbrda.RData")
save(path_sgv_abo_dag3.dbrda.anova, file = "04.SV_abun/path_sgv_abo_dag3.dbrda.anova.RData")

p_path_sgv_abo_dag3.dbrda<-ggord(path_sgv_abo_dag3.dbrda, bt_dag3.rmna$Bloodtype, #vec_lab = new_lab,
      veccol = 'grey50',alpha_el = 0.05,alpha = 0.5,txt = 3,size = 1.5,ext = 1.03,repel = T,labcol = '#e63946',ellipse = FALSE)+
  theme(plot.subtitle = element_text(vjust = 1), 
        plot.caption = element_text(vjust = 1), 
        axis.line.x =  element_line(),
        axis.line.y = element_line(),
        legend.position = 'bottom',
        legend.title = element_blank(),
        legend.key = element_rect(fill = NA), 
        panel.grid.major = element_line(colour = NA),
        panel.grid.minor = element_line(colour = NA),
        panel.background = element_rect(fill = NA))

pdf("04.SV_abun/p_sv_path_dbrda.pdf",width = 5, height = 5)
print(p_path_sgv_abo_dag3.dbrda)
dev.off()

```


## 3 Association between ABO-related SVs and abundance

### 3.1 Species abundance
```{r 3}
## Correlation with all species
mbio_dag3_clr<-abundances(x=as.data.frame(mbio_dag3.rmna), transform="clr") %>%as.data.frame

#sgv_dag3_abo.inter<-sgv_dag3_abo[match(rownames(mbio_dag3), rownames(sgv_dag3_abo)),]
#rownames(sgv_dag3_abo.inter)<-rownames(mbio_dag3)

dag3_covar<-dag3_covar[match(rownames(mbio_dag3_clr), rownames(dag3_covar)),]
rownames(dag3_covar)<-rownames(mbio_dag3_clr)
dag3_covar$s__Faecalibacterium_prausnitzii<-mbio_dag3_clr$s__Faecalibacterium_prausnitzii
dag3_covar<-cbind(dag3_covar, bt_sv_dag3_abo.rmna[,4:6])
dag3_covar$A_antigen_FUT2_secretor_status_interaction<-dag3_covar$A_antigen * dag3_covar$FUT2_secretor_status
dag3_covar$B_antigen_FUT2_secretor_status_interaction<-dag3_covar$B_antigen * dag3_covar$FUT2_secretor_status

covar <- c('ANTHRO.Sex','ANTHRO.AGE','ANTHRO.BMI','META.DNA.conc.ng.ul','META.DNA.postclean.reads', 'META.POOP.COLLECTION_SEASON', 'META.BATCH', 'META.Antibiotics_3m','s__Faecalibacterium_prausnitzii',"A_antigen", "B_antigen", "FUT2_secretor_status", "A_antigen_FUT2_secretor_status_interaction", "B_antigen_FUT2_secretor_status_interaction")

sgv_abo_dag3_abun.lm<-lm_btw_mats(mbio_dag3_clr[,-match('s__Faecalibacterium_prausnitzii', colnames(mbio_dag3_clr))],
                                  sv_dag3_abo.rmna, dag3_covar, covar)
save(sgv_abo_dag3_abun.lm, file = "04.SV_abun/sgv_abo_dag3_abun.lm.RData")
write.table(sgv_abo_dag3_abun.lm, "04.SV_abun/sgv_abo_dag3_abun.lm.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

## visualization
load("04.SV_abun/sgv_abo_dag3_abun.lm.RData")


## heatmap
sgv_abo_dag3_abun_res.sig.edge<-sgv_abo_dag3_abun.lm[sgv_abo_dag3_abun.lm$fdr.p<0.05 &
                                                       sgv_abo_dag3_abun.lm$y_uniq_N>10,] %>%
  .[order(.$p), ]
write.table(sgv_abo_dag3_abun_res.sig.edge, "04.SV_abun/sgv_abo_dag3_abun_res.sig.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

sgv_abo_dag3_abun.p<-reshape(sgv_abo_dag3_abun.lm[,c("Y", "X", "p")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_abun.p)<-as.character(sgv_abo_dag3_abun.p$Y)
sgv_abo_dag3_abun.p<-sgv_abo_dag3_abun.p[,-1]
colnames(sgv_abo_dag3_abun.p)<-str_replace_all(colnames(sgv_abo_dag3_abun.p),"^p.", "")

sgv_abo_dag3_abun.beta<-reshape(sgv_abo_dag3_abun.lm[,c("Y", "X", "Beta")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_abun.beta)<-as.character(sgv_abo_dag3_abun.beta$Y)
sgv_abo_dag3_abun.beta<-sgv_abo_dag3_abun.beta[,-1]
colnames(sgv_abo_dag3_abun.beta)<-str_replace_all(colnames(sgv_abo_dag3_abun.beta),"^Beta.", "")

sgv_abo_dag3_abun.bon<-reshape(sgv_abo_dag3_abun.lm[,c("Y", "X", "fdr.p")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_abun.bon)<-as.character(sgv_abo_dag3_abun.bon$Y)
sgv_abo_dag3_abun.bon<-sgv_abo_dag3_abun.bon[,-1]
colnames(sgv_abo_dag3_abun.bon)<-str_replace_all(colnames(sgv_abo_dag3_abun.bon),"^fdr.p.", "")

sgv_abo_dag3_abun.sgv<-unique(sgv_abo_dag3_abun_res.sig.edge$X) %>% as.character %>% sort
sgv_abo_dag3_abun.spe<-unique(sgv_abo_dag3_abun_res.sig.edge$Y) %>% as.character %>% sort

sgv_abo_dag3_abun.p.plot<-sgv_abo_dag3_abun.p[match(sgv_abo_dag3_abun.spe, rownames(sgv_abo_dag3_abun.p)),
                                            match(sgv_abo_dag3_abun.sgv, colnames(sgv_abo_dag3_abun.p))]
sgv_abo_dag3_abun.bon.plot<-sgv_abo_dag3_abun.bon[match(sgv_abo_dag3_abun.spe, rownames(sgv_abo_dag3_abun.bon)),
                                            match(sgv_abo_dag3_abun.sgv, colnames(sgv_abo_dag3_abun.bon))]
sgv_abo_dag3_abun.beta.plot<-sgv_abo_dag3_abun.beta[match(sgv_abo_dag3_abun.spe, rownames(sgv_abo_dag3_abun.beta)),
                                            match(sgv_abo_dag3_abun.sgv, colnames(sgv_abo_dag3_abun.beta))]
sgv_abo_dag3_abun.sign.plot<-sgv_abo_dag3_abun.bon.plot
sgv_abo_dag3_abun.sign.plot[sgv_abo_dag3_abun.bon.plot<0.05]<-"*"
sgv_abo_dag3_abun.sign.plot[sgv_abo_dag3_abun.bon.plot>=0.05]<-NA

colnames(sgv_abo_dag3_abun.beta.plot)<-colnames(sgv_abo_dag3_abun.beta.plot)%>%str_replace_all(".*:", "")

i  <- 256
myBreaks <- c(seq(min(sgv_abo_dag3_abun.beta.plot), 0, length.out=ceiling(i/2) + 1), 
              seq(max(sgv_abo_dag3_abun.beta.plot)/i, max(sgv_abo_dag3_abun.beta.plot), length.out=floor(i/2)))
pdf("04.SV_abun/sgv_abo_dag3_abun.heatmap.pdf", width = 6, height = 10)
heatmap.2(as.matrix(sgv_abo_dag3_abun.beta.plot),
          col=colorRampPalette(c("#02CBFB","#FFFFFF","#F20C34"))(i), breaks = myBreaks,
          trace = "none", Rowv = F, Colv = F, dendrogram = "none",
          density.info="none",
          cexCol = 1, srtCol = 45, cexRow = 1,
          cellnote = sgv_abo_dag3_abun.sign.plot, notecol = "white",notecex = 2,
          key.title = NA,
          key.xlab = "Beta coefficient",
          key.par=list(mar=c(3.5, 3, 2, 3), # bottom, right, top, left
                       cex.axis = 1, cex.lab = 1), 
          lm=rbind( c(0, 4, 3), c(2, 1, 0 )), 
          lhei = c(0.5, 4),
          lwid=c(0.5, 4, 2 ),
          margins=c(12,5) # ("margin.Y", "margin.X")
)
dev.off()
```


### 3.2 pathway abundance
```{r 3.2}
## Correlation with all species
path_dag3_clr<-abundances(x=as.data.frame(path_dag3.rmna), transform="clr") %>%as.data.frame

#sgv_dag3_abo.inter<-sgv_dag3_abo[match(rownames(path_dag3), rownames(sgv_dag3_abo)),]
#rownames(sgv_dag3_abo.inter)<-rownames(path_dag3)

sgv_abo_dag3_path.lm<-lm_btw_mats(path_dag3_clr,sv_dag3_abo.rmna, dag3_covar, covar)
save(sgv_abo_dag3_path.lm, file = "04.SV_abun/sgv_abo_dag3_path.lm.RData")
write.table(sgv_abo_dag3_path.lm, "04.SV_abun/sgv_abo_dag3_path.lm.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

## visualization
load("04.SV_abun/sgv_abo_dag3_path.lm.RData")

## heatmap
sgv_abo_dag3_path_res.sig.edge<-sgv_abo_dag3_path.lm[sgv_abo_dag3_path.lm$fdr.p<0.05 &
                                                       sgv_abo_dag3_path.lm$y_uniq_N>10,] %>%
  .[order(.$p), ]
write.table(sgv_abo_dag3_path_res.sig.edge, "04.SV_abun/sgv_abo_dag3_path_res.sig.tsv",sep = "\t", row.names = F, col.names = T, quote = F)

sgv_abo_dag3_path.p<-reshape(sgv_abo_dag3_path.lm[,c("Y", "X", "p")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_path.p)<-as.character(sgv_abo_dag3_path.p$Y)
sgv_abo_dag3_path.p<-sgv_abo_dag3_path.p[,-1]
colnames(sgv_abo_dag3_path.p)<-str_replace_all(colnames(sgv_abo_dag3_path.p),"^p.", "")

sgv_abo_dag3_path.beta<-reshape(sgv_abo_dag3_path.lm[,c("Y", "X", "Beta")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_path.beta)<-as.character(sgv_abo_dag3_path.beta$Y)
sgv_abo_dag3_path.beta<-sgv_abo_dag3_path.beta[,-1]
colnames(sgv_abo_dag3_path.beta)<-str_replace_all(colnames(sgv_abo_dag3_path.beta),"^Beta.", "")

sgv_abo_dag3_path.bon<-reshape(sgv_abo_dag3_path.lm[,c("Y", "X", "fdr.p")],idvar = "Y", timevar = "X", direction = "wide")
rownames(sgv_abo_dag3_path.bon)<-as.character(sgv_abo_dag3_path.bon$Y)
sgv_abo_dag3_path.bon<-sgv_abo_dag3_path.bon[,-1]
colnames(sgv_abo_dag3_path.bon)<-str_replace_all(colnames(sgv_abo_dag3_path.bon),"^fdr.p.", "")

sgv_abo_dag3_path.sgv<-unique(sgv_abo_dag3_path_res.sig.edge$X) %>% as.character %>% sort
sgv_abo_dag3_path.spe<-unique(sgv_abo_dag3_path_res.sig.edge$Y) %>% as.character %>% sort

sgv_abo_dag3_path.p.plot<-sgv_abo_dag3_path.p[match(sgv_abo_dag3_path.spe, rownames(sgv_abo_dag3_path.p)),
                                            match(sgv_abo_dag3_path.sgv, colnames(sgv_abo_dag3_path.p))]
sgv_abo_dag3_path.bon.plot<-sgv_abo_dag3_path.bon[match(sgv_abo_dag3_path.spe, rownames(sgv_abo_dag3_path.bon)),
                                            match(sgv_abo_dag3_path.sgv, colnames(sgv_abo_dag3_path.bon))]
sgv_abo_dag3_path.beta.plot<-sgv_abo_dag3_path.beta[match(sgv_abo_dag3_path.spe, rownames(sgv_abo_dag3_path.beta)),
                                            match(sgv_abo_dag3_path.sgv, colnames(sgv_abo_dag3_path.beta))]
sgv_abo_dag3_path.sign.plot<-sgv_abo_dag3_path.bon.plot
sgv_abo_dag3_path.sign.plot[sgv_abo_dag3_path.bon.plot<0.05]<-"*"
sgv_abo_dag3_path.sign.plot[sgv_abo_dag3_path.bon.plot>=0.05]<-NA

colnames(sgv_abo_dag3_path.beta.plot)<-colnames(sgv_abo_dag3_path.beta.plot)%>%str_replace_all(".*:", "")

i  <- 256
myBreaks <- c(seq(min(sgv_abo_dag3_path.beta.plot), 0, length.out=ceiling(i/2) + 1), 
              seq(max(sgv_abo_dag3_path.beta.plot)/i, max(sgv_abo_dag3_path.beta.plot), length.out=floor(i/2)))
pdf("04.SV_abun/sgv_abo_dag3_path.heatmap.pdf", width = 8, height = 40)
heatmap.2(as.matrix(sgv_abo_dag3_path.beta.plot),
          col=colorRampPalette(c("#02CBFB","#FFFFFF","#F20C34"))(i), breaks = myBreaks,
          trace = "none", Rowv = F, Colv = F, dendrogram = "none",
          density.info="none",
          cexCol = 1, srtCol = 45, cexRow = 1,
          cellnote = sgv_abo_dag3_path.sign.plot, notecol = "white",notecex = 2,
          key.title = NA,
          key.xlab = "Beta coefficient",
          key.par=list(mar=c(3.5, 1, 2, 1), # bottom, right, top, left
                       cex.axis = 1, cex.lab = 1), 
          lm=rbind( c(0, 4, 3), c(2, 1, 0 )), 
          lhei = c(0.5, 4),
          lwid=c(0.5, 4, 8 ),
          margins=c(12,5) # ("margin.Y", "margin.X")
)
dev.off()
```
