---
title: "Validation based on metaX data"
author: "Daoming Wang"
date: "2021/03/25"
output:
  html_document: 
    theme: flatly
    highlight: espresso
    toc: true
    toc_depth: 4
    toc_float: true
  word_document: default
  pdf_document:
    includes:
      in_header: header.tex
      keep_tex: yes
      latex_engine: xelatex
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 Preparation
### 1.1 Import

```{r 1.1, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
suppressMessages(source("functions.R"))
```

### 1.2 Inputs

```{r 1.2, echo=TRUE}
load("01.cleanData/assoc_SV/dsgv_hmp2_full_assoc.RData")
load("01.cleanData/assoc_SV/vsgv_hmp2_full_assoc.RData")

load("01.cleanData/assoc_SV/dsgv_hmp2_full_abo.RData")
load("01.cleanData/assoc_SV/vsgv_hmp2_full_abo.RData")

load("01.cleanData/hmp2/metatrans_path_hmp2_nonIBD.RData")
load("01.cleanData/hmp2/metatrans_ec3_hmp2_nonIBD.RData")
load("01.cleanData/hmp2/metatrans_gene_fp_hmp2_nonIBD.RData")

info_hmp2_nonIBD_metageno<-read.csv("01.cleanData/hmp2/info_hmp2_nonIBD_metageno.tsv", sep = "\t", header = T, quote = "")
metatrans_gene_fp_hmp2.anno<-read.csv("00.rawData/hmp2/uniprot-yourlist_M202203294ABAA9BC7178C81CEBC9459510EDDEA347ED0FY.tab",
                                      sep = "\t", header = T, quote = "")
```

### 1.3 Preparation

```{r 1.3}
# All associated SVs
sgv_hmp2_full_assoc<-cbind(dsgv_hmp2_full_assoc, vsgv_hmp2_full_assoc)
sgv_hmp2_nonIBD_assoc<-sgv_hmp2_full_assoc[match(info_hmp2_nonIBD_metageno$External.ID, rownames(sgv_hmp2_full_assoc)),]
rownames(sgv_hmp2_nonIBD_assoc)<-info_hmp2_nonIBD_metageno$External.ID

sgv_hmp2_nonIBD_assoc<-sgv_hmp2_nonIBD_assoc[,colSums(!is.na(sgv_hmp2_nonIBD_assoc))>100]

sgv_hmp2_full_assoc.spe<-colnames(sgv_hmp2_nonIBD_assoc) %>% sort %>%str_replace_all("\\:.*", "") %>%table%>%sort(decreasing = T) 
sgv_hmp2_full_assoc.spe<-data.frame(SV_species_name=names(sgv_hmp2_full_assoc.spe),
                                    Assoc_SV_N = as.numeric(sgv_hmp2_full_assoc.spe))
sgv_hmp2_full_assoc.spe$HMP2_name<-c("Bacteroides_uniformis","Eubacterium_rectale","Faecalibacterium_prausnitzii","Roseburia_intestinalis",
                                     "Bacteroides_xylanisolvens", "Alistipes_putredinis", "Bacteroides_massiliensis", NA,
                                     "Eubacterium_siraeum", "Parabacteroides_distasonis", "Parabacteroides_merdae")

sgv_hmp2_full_assoc.spe<-sgv_hmp2_full_assoc.spe[sgv_hmp2_full_assoc.spe$Assoc_SV_N>1 & !is.na(sgv_hmp2_full_assoc.spe$HMP2_name),]

# ABO-associated SVs
sgv_hmp2_full_abo<-cbind(dsgv_hmp2_full_abo, vsgv_hmp2_full_abo)
sgv_hmp2_nonIBD_abo<-sgv_hmp2_full_abo[match(info_hmp2_nonIBD_metageno$External.ID, rownames(sgv_hmp2_full_abo)),]
rownames(sgv_hmp2_nonIBD_abo)<-info_hmp2_nonIBD_metageno$External.ID
if(!dir.exists("06.SV_metaX")){dir.create("06.SV_metaX")}
```

## 2 Association with ABO-associated SV

### 2.1 Pathway level

```{r 2.1}
hmp2_covar<-c("reads_filtered", "consent_age")
hmp2_random<-c("site_name","Participant.ID")

metatrans_path_hmp2_nonIBD_sv_lmm<-NULL
for (i in 1:nrow(sgv_hmp2_full_assoc.spe)) {
  if(is.na(sgv_hmp2_full_assoc.spe$HMP2_name[i])){
    next
  }
  cat(i,sgv_hmp2_full_assoc.spe$HMP2_name[i],"\n")
  sgv_hmp2_nonIBD_assoc_i<-sgv_hmp2_nonIBD_assoc[,grep(sgv_hmp2_full_assoc.spe$SV_species_name[i],colnames(sgv_hmp2_nonIBD_assoc))]
  if(is.null(dim(sgv_hmp2_nonIBD_assoc_i))){
    sgv_hmp2_nonIBD_assoc_i<-as.data.frame(sgv_hmp2_nonIBD_assoc_i)
    colnames(sgv_hmp2_nonIBD_assoc_i)<-colnames(sgv_hmp2_nonIBD_assoc)[grep(sgv_hmp2_full_assoc.spe$SV_species_name[i],colnames(sgv_hmp2_nonIBD_assoc))]
  }
  if(dim(sgv_hmp2_nonIBD_assoc_i)[2]==0){
    next
  }
  metatrans_path_hmp2_nonIBD_i<-metatrans_path_hmp2_nonIBD[,grep(sgv_hmp2_full_assoc.spe$HMP2_name[i], colnames(metatrans_path_hmp2_nonIBD))]
  
  metatrans_path_hmp2_nonIBD_sv_lmm_i<-lmm_btw_mats(metatrans_path_hmp2_nonIBD_i, sgv_hmp2_nonIBD_assoc_i, info_hmp2_nonIBD_metageno, hmp2_covar, hmp2_random)
  metatrans_path_hmp2_nonIBD_sv_lmm<-rbind(metatrans_path_hmp2_nonIBD_sv_lmm, metatrans_path_hmp2_nonIBD_sv_lmm_i)
}



#metatrans_path_hmp2_nonIBD_sv_lmm<-lmm_btw_mats(metatrans_path_hmp2_nonIBD, sgv_hmp2_nonIBD_abo, info_hmp2_nonIBD_metageno, c("reads_filtered", "consent_age"), "Participant.ID")
save(metatrans_path_hmp2_nonIBD_sv_lmm, file = "06.SV_metaX/metatrans_path_hmp2_nonIBD_sv_lmm.RData")
load("06.SV_metaX/metatrans_path_hmp2_nonIBD_sv_lmm.RData")

metatrans_path_hmp2_nonIBD_sv_lmm$p[metatrans_path_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_path_hmp2_nonIBD_sv_lmm$Beta[metatrans_path_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_path_hmp2_nonIBD_sv_lmm$SE[metatrans_path_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_path_hmp2_nonIBD_sv_lmm$fdr.p<-p.adjust(metatrans_path_hmp2_nonIBD_sv_lmm$p, method = "BH")
metatrans_path_hmp2_nonIBD_sv_lmm$bonferroni.p<-p.adjust(metatrans_path_hmp2_nonIBD_sv_lmm$p, method = "bonferroni")


metatrans_path_hmp2_nonIBD_sv_lmm$SigAssoc<-"No"
metatrans_path_hmp2_nonIBD_sv_lmm$SigAssoc[metatrans_path_hmp2_nonIBD_sv_lmm$fdr.p<0.1]<-"Yes"

pdf("06.SV_metaX/metatrans_path_hmp2_nonIBD_sv_lmm.volcano.pdf",width = 7, height = 3.5)
ggplot(metatrans_path_hmp2_nonIBD_sv_lmm,aes(Beta, -log10(p), color=SigAssoc))+
  geom_point(alpha = 0.5,size = 1)+
  xlab('Beta coefficient')+
  ylab('-log10(P)')+
  scale_color_manual(name   = NULL,
                     breaks = c("Yes", "No"),
                     labels = c("Associated    ", "Not associated"),
                     values = c("#ff4040","#4f94cd"))+
  scale_shape_discrete(name = NULL)+
  theme_bw()+
  theme(legend.position = "right",
        legend.key = element_rect(fill = NA))
dev.off()

write.table(metatrans_path_hmp2_nonIBD_sv_lmm, "06.SV_metaX/metatrans_path_hmp2_nonIBD_sv_lmm.tsv",
            sep = "\t", row.names = F, col.names = T, quote = F)
```

### 2.2 Enzyme/reaction level

```{r 2.2}

metatrans_ec3_hmp2_nonIBD_sv_lmm<-NULL
for (i in 1:nrow(sgv_hmp2_full_assoc.spe)) {
  if(is.na(sgv_hmp2_full_assoc.spe$HMP2_name[i])){
    next
  }
  cat(i,sgv_hmp2_full_assoc.spe$HMP2_name[i],"\n")
  sgv_hmp2_nonIBD_assoc_i<-sgv_hmp2_nonIBD_assoc[,grep(sgv_hmp2_full_assoc.spe$SV_species_name[i],colnames(sgv_hmp2_nonIBD_assoc))]
  if(is.null(dim(sgv_hmp2_nonIBD_assoc_i))){
    sgv_hmp2_nonIBD_assoc_i<-as.data.frame(sgv_hmp2_nonIBD_assoc_i)
    colnames(sgv_hmp2_nonIBD_assoc_i)<-colnames(sgv_hmp2_nonIBD_assoc)[grep(sgv_hmp2_full_assoc.spe$SV_species_name[i],colnames(sgv_hmp2_nonIBD_assoc))]
  }
  if(dim(sgv_hmp2_nonIBD_assoc_i)[2]==0){
    next
  }
  metatrans_ec3_hmp2_nonIBD_i<-metatrans_ec3_hmp2_nonIBD[,grep(sgv_hmp2_full_assoc.spe$HMP2_name[i], colnames(metatrans_ec3_hmp2_nonIBD))]
  
  metatrans_ec3_hmp2_nonIBD_sv_lmm_i<-lmm_btw_mats(metatrans_ec3_hmp2_nonIBD_i, sgv_hmp2_nonIBD_assoc_i, info_hmp2_nonIBD_metageno, hmp2_covar, hmp2_random)
  metatrans_ec3_hmp2_nonIBD_sv_lmm<-rbind(metatrans_ec3_hmp2_nonIBD_sv_lmm, metatrans_ec3_hmp2_nonIBD_sv_lmm_i)
}

save(metatrans_ec3_hmp2_nonIBD_sv_lmm, file = "06.SV_metaX/metatrans_ec3_hmp2_nonIBD_sv_lmm.RData")
load("06.SV_metaX/metatrans_ec3_hmp2_nonIBD_sv_lmm.RData")

metatrans_ec3_hmp2_nonIBD_sv_lmm$p[metatrans_ec3_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_ec3_hmp2_nonIBD_sv_lmm$Beta[metatrans_ec3_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_ec3_hmp2_nonIBD_sv_lmm$SE[metatrans_ec3_hmp2_nonIBD_sv_lmm$y_uniq_N<10]<-NA
metatrans_ec3_hmp2_nonIBD_sv_lmm$fdr.p<-p.adjust(metatrans_ec3_hmp2_nonIBD_sv_lmm$p, method = "BH")
metatrans_ec3_hmp2_nonIBD_sv_lmm$bonferroni.p<-p.adjust(metatrans_ec3_hmp2_nonIBD_sv_lmm$p, method = "bonferroni")

metatrans_ec3_hmp2_nonIBD_sv_lmm$SigAssoc<-"No"
metatrans_ec3_hmp2_nonIBD_sv_lmm$SigAssoc[metatrans_ec3_hmp2_nonIBD_sv_lmm$fdr.p<0.05]<-"Yes"

pdf("06.SV_metaX/metatrans_ec3_hmp2_nonIBD_sv_lmm.volcano.pdf",width = 7, height = 3.5)
ggplot(metatrans_ec3_hmp2_nonIBD_sv_lmm,aes(Beta, -log10(p), color=SigAssoc))+ # ,shape = X
  geom_point(alpha = 0.5,size = 1)+
  xlab('Beta coefficient')+
  ylab('-log10(P)')+
  scale_color_manual(name   = NULL,
                     breaks = c("Yes", "No"),
                     labels = c("Associated    ", "Not associated"),
                     values = c("#ff4040","#4f94cd"))+
  scale_shape_discrete(name = NULL)+
  theme_bw()+
  theme(legend.position = "right",
        legend.key = element_rect(fill = NA))
dev.off()

write.table(metatrans_ec3_hmp2_nonIBD_sv_lmm, "06.SV_metaX/metatrans_ec3_hmp2_nonIBD_sv_lmm.tsv",
            sep = "\t", row.names = F, col.names = T, quote = F)
```


### 2.3 Gene family level

```{r 2.3}
metatrans_gene_hmp2_nonIBD_fp_sv_lmm<-lmm_btw_mats(metatrans_gene_fp_hmp2_nonIBD, sgv_hmp2_nonIBD_abo, info_hmp2_nonIBD_metageno, hmp2_covar, hmp2_random)
save(metatrans_gene_hmp2_nonIBD_fp_sv_lmm, file = "06.SV_metaX/metatrans_gene_hmp2_nonIBD_fp_sv_lmm.RData")
load("06.SV_metaX/metatrans_gene_hmp2_nonIBD_fp_sv_lmm.RData")

metatrans_gene_hmp2_nonIBD_fp_sv_lmm$p[metatrans_gene_hmp2_nonIBD_fp_sv_lmm$y_uniq_N<10]<-NA
metatrans_gene_hmp2_nonIBD_fp_sv_lmm$Beta[metatrans_gene_hmp2_nonIBD_fp_sv_lmm$y_uniq_N<10]<-NA
metatrans_gene_hmp2_nonIBD_fp_sv_lmm$SE[metatrans_gene_hmp2_nonIBD_fp_sv_lmm$y_uniq_N<10]<-NA
metatrans_gene_hmp2_nonIBD_fp_sv_lmm$fdr.p<-p.adjust(metatrans_gene_hmp2_nonIBD_fp_sv_lmm$p, method = "BH")
metatrans_gene_hmp2_nonIBD_fp_sv_lmm$bonferroni.p<-p.adjust(metatrans_gene_hmp2_nonIBD_fp_sv_lmm$p, method = "bonferroni")

metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno<-left_join(metatrans_gene_hmp2_nonIBD_fp_sv_lmm, metatrans_gene_fp_hmp2.anno, by = c("Y" = "Entry"))
metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno$SigAssoc<-"No"
metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno$SigAssoc[metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno$fdr.p<0.05]<-"Yes"

pdf("06.SV_metaX/metatrans_gene_hmp2_nonIBD_fp_sv_lmm.volcano.pdf",width = 7, height = 3.5)
ggplot(metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno,aes(Beta, -log10(p), color=SigAssoc,shape = X))+
  geom_point(alpha = 0.5,size = 1)+
  xlab('Beta coefficient')+
  ylab('-log10(P)')+
  scale_color_manual(name   = NULL,
                     breaks = c("Yes", "No"),
                     labels = c("Associated    ", "Not associated"),
                     values = c("#ff4040","#4f94cd"))+
  scale_shape_discrete(name = NULL)+
  theme_bw()+
  theme(legend.position = "right",
        legend.key = element_rect(fill = NA))
dev.off()

write.table(metatrans_gene_hmp2_nonIBD_fp_sv_lmm, "06.SV_metaX/metatrans_gene_hmp2_nonIBD_fp_sv_lmm.tsv",
            sep = "\t", row.names = F, col.names = T, quote = F)
write.table(metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno, "06.SV_metaX/metatrans_gene_hmp2_nonIBD_fp_sv_lmm.anno.tsv",
            sep = "\t", row.names = F, col.names = T, quote = F)

##


# 577_579 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$C7H7H2,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:577_579`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_577_alpha_galactosamine.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "577_579 and alpha-galactosamine",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()


# 1154_1155 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$C7H7H2,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:1154_1155`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_1154_alpha_galactosamine.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "1154_1155 and alpha-galactosamine",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()

# 1154_1155 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$C7H7H2,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:1154_1155`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_1154_alpha_galactosamine.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "1154_1155 and alpha-galactosamine",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()


# 2910_2911 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$C7H7H2,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:2910_2911`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_2910_alpha_galactosamine.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "2910_2911 and alpha-galactosamine",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()

#
df<-data.frame(Expression = qtrans(as.numeric(metatrans_gene_fp_hmp2_nonIBD$C7H7H2)),
               SV = qtrans(as.numeric(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:885_887`))) %>% na.omit

cor_res<-cor.test(df$Expression,df$SV)
text_r<-paste("R=", signif(cor_res$estimate, digits = 3) ,
              ",\nP=",signif(cor_res$p.value, digits = 3),sep = "")
pdf("06.SV_metaX/Example_vsv_Fp_885_alpha_galactosamine.pdf", height = 4, width = 4)
ggplot(df, aes(x = SV,y = Expression))+
  geom_point(alpha = 0.5)+
  geom_smooth(method = 'lm', linetype = 'dashed')+
  ylab("Standardized Expression")+
  xlab("Standardized SV coverage")+
#  ylim(0.001, 0.4)+
#  scale_y_continuous(trans = 'log10', limits = c(0.005, 0.4))+
#  scale_x_log10()+
  ggtitle("885_887 and alpha-galactosamine")+
  theme_minimal()
dev.off()

#
# 2910_2911 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$C7H801,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:2910_2911`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_2910_tat.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "2910_2911 and Tat pathway signal sequence domain protein",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()

# 577_579 and alpha-galactosamine
metatrans_gene_fp_hmp2_nonIBD<-as.data.frame(metatrans_gene_fp_hmp2_nonIBD)
df<-data.frame(Expression = metatrans_gene_fp_hmp2_nonIBD$A8SDI2,
               SV = as.factor(sgv_hmp2_nonIBD_abo$`Faecalibacterium cf. prausnitzii KLE1255:577_579`)) %>% na.omit

pdf("06.SV_metaX/Example_dsv_Fp_577_toxin.pdf",width = 3, height = 4)
ggviolin(df, x = "SV", y = "Expression", fill = "SV",color = "SV", 
         title = "577_579 and Addiction module toxin, RelE/StbE family",
         #palette = blue_yellow_green_red, 
         add.width = 1,width = 1,
         add = c("boxplot"), add.params = list(fill = "white", width = 0.1))+
  scale_fill_manual(breaks = c(0,1),
                    labels = c("Absence", "Presence"))+
  scale_x_discrete(breaks = c(0,1),
                   labels = c("Absence", "Presence"))+
  scale_y_log10()+
  xlab(NULL)+
  ylab("Expression")+ # xxx  ARGs Shannon index   ARGs count
  theme_classic2()+
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5,size = 6))+
  scale_fill_npg()+
  scale_color_npg()
dev.off()


```
